services:
  app:
    container_name: milove
    volumes:
      - .:/api-server
    build: .
    ports:
      - '9999:9999'
    env_file:
      - .env.local
    depends_on:
      - db

  db:
    container_name: milove-db
    image: ankane/pgvector
    ports:
      - '5433:5432'
    env_file:
      - .env.local
    volumes:
      - db-data:/var/lib/postgresql/data

volumes:
  db-data: